# Qui êtes-vous ?
<div class="alert alert-block alert-info">
Écrire ci-dessous le nom, le prénom et le numéro étudiant de chaque membre du binôme :
</div>

In [1]:
# Vu Hoang Thuy Duong - 21110221 SCFO

# TME 06X - Variables discrètes

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

## 1 - Manipulation d'une loi de probabilité jointe

<div class="alert alert-block alert-warning">
Soit deux variables aléatoires $X$ et $Y$ qui suivent la loi de probabilité jointe suivante :
$$
    \begin{array}{c|cccc}
      p_{XY}(x, y) & 0 & 1 & 2 & 3 \\
      \hline
      0 & \frac{9}{32} & \frac{3}{32} & \frac{1}{32} & \frac{7}{32} \\
      1 & \frac{1}{32} & \frac{2}{32} & \frac{8}{32} & \frac{1}{32}
    \end{array}
$$
</div>

<div class="alert alert-block alert-info">
Q1.1 - Déclarer un tableau <code>pxy</code> représentant cette loi de probabilité jointe.
</div>

In [32]:
pxy = np.array([
    [9/32,3/32,1/32,7/32],
    [1/32,2/32,8/32,1/32]
])
pxy

array([[0.28125, 0.09375, 0.03125, 0.21875],
       [0.03125, 0.0625 , 0.25   , 0.03125]])

<div class="alert alert-block alert-info">
Q1.2 - Écrire une fonction <code>est_proba</code> qui prend en paramètre un tableau numpy et qui renvoie <code>True</code> s'il s'agit d'une loi de probabilité jointe (et <code>False</code> sinon).
    
On vérifira que chaque valeur est comprise entre 0 et 1 et que la somme vaut 1 (à $\epsilon$ près si nécessaire).
</div>

In [23]:
def est_proba(X) :
    return (np.sum(X) == 1 and 0 <= X.all() <= 1)

<div class="alert alert-block alert-warning">
On rappelle qu'on peut accéder à des sous-parties d'un tableau numpy avec la syntaxe suivante (pour <code>pxy</code>) :
<ul>
    <li><code>pxy[1, 2]</code> renvoie la donnée située à la ligne 1 et à la colonne 2</li>
    <li><code>pxy[0:2, 2]</code> renvoie toute la colonne 2</li>
    <li><code>pxy[0, 0:4]</code> renvoie toute la ligne 0</li>
</ul>
</div>

<div class="alert alert-block alert-info">
Q1.3 - Calculer la loi marginale de $X$ dans un tableau <code>px</code>.
</div>

In [29]:
px = np.array([np.sum(pxy[0]),np.sum(pxy[1])])
px

array([0.625, 0.375])

<div class="alert alert-block alert-info">
Q1.4 - Calculer la loi marginale de $Y$ dans un tableau <code>py</code>.
</div>

In [46]:
py = np.array([np.sum(pxy[:, 0]), np.sum(pxy[:, 1]), np.sum(pxy[:, 2]), np.sum(pxy[:, 3])])
py

array([0.3125 , 0.15625, 0.28125, 0.25   ])

<div class="alert alert-block alert-info">
Q1.5 - Calculer la loi $p_X \times p_y$ dans un tableau <code>pxpy</code>.
</div>

In [47]:
pxpy = [[],[]]
for i in range(len(px)):
    for j in range(len(py)):
        pxpy[i].append(px[i]*py[j])
pxpy

[[0.1953125, 0.09765625, 0.17578125, 0.15625],
 [0.1171875, 0.05859375, 0.10546875, 0.09375]]

<div class="alert alert-block alert-info">
Q1.6 - $X$ et $Y$ sont-elles indépendantes ?
</div>

In [48]:
np.cov(pxpy[0],pxpy[1])
# Comme le covariance de X et Y n'est pas égale à 0, X et Y ne sont pas indépendantes

array([[0.00178019, 0.00106812],
       [0.00106812, 0.00064087]])

<div class="alert alert-block alert-info">
Q1.7 - Écrire une fonction qui prend en paramètre un tableau représentant une loi de probabilité jointe de deux variables aléatoires discrètes et qui renvoie <code>True</code> si ces variables sont indépendantes (et <code>False</code> sinon).
</div>

In [49]:
def est_indep(pxy, pxpy, eps):
    
    return (np.abs(pxy - pxpy)).all() < eps

<div class="alert alert-block alert-info">
Q1.8 - Écrire une instruction qui teste votre fonction sur <code>pxy</code> et sur <code>pxpy</code>.
</div>

In [50]:
est_indep(pxy, pxpy, 1e-8)

False

## 2 - Probablités conditionnelles

<div class="alert alert-block alert-warning">
Dans cette partie, nous allons continuer de travailler avec la loi jointe <code>pxy</code>.
</div>

<div class="alert alert-block alert-info">
Q2.1 - Calculer la loi conditionnelle $p_{X|Y}(x)$ dans un tableau <code>pxSy</code>.
</div>

In [51]:
pxSy = pxy/py
pxSy

array([[0.9       , 0.6       , 0.11111111, 0.875     ],
       [0.1       , 0.4       , 0.88888889, 0.125     ]])

<div class="alert alert-block alert-info">
Q2.2 - De même, calculer la loi conditionnelle $p_{Y|X}(y)$ dans un tableau <code>pySx</code>.
</div>

In [52]:
pySx = (pxy.T/px).T

<div class="alert alert-block alert-info">
Q2.3 - Chaque calcul précédent permet-il de dire si les variables $X$ et $Y$ sont indépendantes ?
</div>

In [53]:
# Oui, car si les probas conditionnelles de ces 2 variables sont différentes de 0, ils sont dépendantes

## 3 - Espérance et variance

<div class="alert alert-block alert-warning">
Nous allons supposer que les réalisations de la variable $X$ correspondent aux indices de lignes et que les réalisations de la variable $Y$ correspondent aux indices de colonnes.
</div>

<div class="alert alert-block alert-info">
Q3.1 - Écrire une fonction <code>esperance</code> qui calcule l'espérance d'une variable aléatoire dont la loi <code>p</code> est donnée sous la forme d'un tableau numpy unidimensionnel.
</div>

In [61]:
def esperance(p):
    return np.sum([i * p[i] for i in range(len(p))])

<div class="alert alert-block alert-info">
Q3.2 - Calculer l'espérance de la variable $Y$.
</div>

In [62]:
esperance(py)

1.46875

<div class="alert alert-block alert-info">
Q3.3 - Calculer les espérances conditionnelles de $Y$ sachant $X = x$ pour $0 \leqslant x < 2$.
</div>

In [63]:
np.array([esperance(pySx[i, 0:4]) for i in range(0, 2)])

array([1.3 , 1.75])

<div class="alert alert-block alert-warning">
Pour allons à présent calculer des espérances sur la loi jointe. Pour cela, nous passerons en paramètres une fonction de $x$ et de $y$ qui renvoie un réel.
    
Par exemple, nous allons commencer par calculer l'espérance de $X + Y$.
</div>

<div class="alert alert-block alert-info">
Exécuter le bloc suivant qui définit la fonction <code>fsom</code>.
</div>

In [64]:
def fsom(x, y):
    return x + y

<div class="alert alert-block alert-info">
Q3.4 - Écrire une fonction <code>esperance_jointe</code> prend en paramètres une loi jointe de deux variables <code>p</code> et une fonction de deux variables <code>f</code> et qui calcule l'espérance de $f(X, Y)$.
</div>

In [66]:
def esperance_jointe(p,f):
    px = []
    for i in range(len(p)):
        px.append(np.sum(p[i]))
    px = np.array(px)
    
    py = []
    for j in range(len(p[0])):
        py.append(np.sum(p[:,j]))
    py = np.array(py)
    return f(esperance(px),esperance(py))

<div class="alert alert-block alert-info">
Q3.5 - Calculer $\mathbb{E}(X + Y)$.
</div>

In [67]:
esperance_jointe(pxy,fsom)

1.84375

<div class="alert alert-block alert-info">
Q3.6 - Calculer $\mathbb{E}(XY)$.
</div>

In [70]:
def fprod(x, y):
    return x * y

esperance_jointe(pxy, fprod)

0.55078125

<div class="alert alert-block alert-info">
Q3.7- Écrire une fonction <code>covariance</code> prend en paramètres une loi jointe de deux variables <code>p</code> et qui renvoie la covariance de $X$ et $Y$.
</div>

In [74]:
def covariance(p):
    return esperance_jointe(p,fprod) - esperance_jointe(p,fsom)

<div class="alert alert-block alert-info">
Q3.8 - Calculer $\mathbb{C}ov(X, Y)$.
</div>

In [75]:
covariance(pxy)

-1.29296875

---